### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by zacharyblank** [mranney/node_pcap#112]
Is there a way to implement HTTPS support? No certs needed really or anything advanced, just want to see https request urls.

Thanks!

**Comment by mranney** [comment]
This is something that wireshark knows how to do, but it's pretty complicated. If somebody wanted to take a crack at an implementation for node_pcap, I'd be eager to try it. Until then, I think you are stuck with one of the various mitm proxies out there.

**Comment by brannondorsey** [comment]
@unixpickle @filipenf I am looking for the easiest way to resolve all hostnames for TCP/IP traffic. Is there built in functionality to do this or would I have to manually track DNS lookups myself?

**Comment by filipenf** [comment]
@brannondorsey the easiest ( and more efficient ) way to do that is to grab all DNS responses for a .cap file.

However, this will leave gaps if the traffic is partially captured and the DNS resolution happened before the traffic capture started or if the clients connect directly to servers' ip addresses not their hostnames ( unusual, but possible )

You can also try to use reverse DNS to try to find out what is the name of this IP ( but this is a somewhat expensive operation and also is not precise because on IP may be associated with multiple host names )

**Comment by brannondorsey** [comment]
@filipenf, thanks for the speedy reply! I was looking into reverse DNS as another method. I hadn't thought of the issue of multiple domains to each IP.

When on a LAN, is every DNS request (accept for loopback and hostnames on the LAN) sent through the Gateway? Or does the browser cache DNS results and possibly not expose them via Wifi?

I am trying to create a small network auditing script that tracks HTTP and HTTPS domain names visited by certain hosts. Either method mentioned above will give somewhat cloudy results as any asset loaded on a page will make another DNS request. Going to say, <https://amazon.com>, actually triggers ~20 hostname lookups. Is there any sensical method of separating hostnames visited by a browser from ones that are requested simply for assets?

**Comment by filipenf** [comment]
Yes, you can do that. You just need to keep a hashmap of ip addresses => domain names so when you are parsing your .cap file, you can infer what are the hostnames for each ip packet. This can give you a pretty good idea of what is going on in your network. Of course it has some problems ( like I've mentioned before one IP address may be associated with multiple domain names ) but I think you can workaround them pretty easily.

If you need more details feel free to get in touch with private messages ( maybe this isn't the best to discuss it ;-) )
