### ISSUE TITLE
http_trace is not working

### ISSUE THREAD

**Issue by jpacora** [mranney/node_pcap#160]
The http events is never fired! I'm using Mac OS X Yosemite

**Comment by jmaxxz** [comment]
see #119 http_trace is no long part of this repository. See https://github.com/mranney/http_trace for an example of how to decode http traffic.

**Comment by jpacora** [comment]
Then remove that of README

**Comment by jmaxxz** [comment]
First let me welcome you to open source. Secondly let me say you sir need to calm down. If you have a change you think improves things submit it. If you have a passion for updating readme do it. What is not productive is simply pointing out things which are not done because they are not done and offering no solutions.

As you can see from the [contributor graph](https://github.com/mranney/node_pcap/graphs/contributors) this project has not received a lot of love for some time. A very active effort is underway to update it and bring out a new version, which will include updated documentation. Acting entitled to contributors time will not win you any friends and certainly will not result in you being taken seriously.

If you would like to offer meaningful contributions via pull requests I would be more than happy to take the time to merge them in.
