### ISSUE TITLE
Make Pcap a readable stream

### ISSUE THREAD

**Issue by DanielBaulig** [mranney/node_pcap#30]
I would like to propose to make Pcap a readable stream. That way it could interface better with the streaming model node uses for basically all other i/o.
If there is support for this I might have a look at it.

**Comment by mranney** [comment]
The problem here is that we emit all kinds of things, not just "data", so I don't think it makes sense as a readable stream. If you want readable stream semantics, you'll have to decide for yourself what event you consider the data. I think this would be better done in a separate module based on the protocol or other behavior you want to capture.
